datasets:
  TC:
    data_type: images

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: datasets/TC/annotations/TC_train.json
          storage: datasets/TC/annotations/TC_train.json
      images:
          storage: datasets/TC/slices