model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "Llama-2-7b-chat-hf"
  ckpt: "checkpoints/tumor_classification/20250904153/checkpoint_23.pth" #/pancreas_detection/20250806153/checkpoint_11.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  MSD_tumor_detection: #MSD_pancreas_detection:
    batch_size: 16
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 100
  #MSD_pancreas_detection: #MSD_pancreas_detection_balanced:
  #  batch_size: 16
  #  vis_processor:
  #    train:
  #      name: "blip2_image_train"
  #      image_size: 448
  #  text_processor:
  #    train:
  #      name: "blip_caption"
  #  sample_ratio: 100

  #NIH_pancreas_detection: #NIH_pancreas_detection_balanced:
  #  batch_size: 16
  #  vis_processor:
  #    train:
  #      name: "blip2_image_train"
  #      image_size: 448
  #  text_processor:
  #    train:
  #      name: "blip_caption"
  #  sample_ratio: 100
  #TC:
  #  batch_size: 16
  #  vis_processor:
  #    train:
  #      name: "blip2_image_train"
  #      image_size: 448
  #  text_processor:
  #    train:
  #      name: "blip_caption"
  #  sample_ratio: 100

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 50
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "../checkpoints/tumor_detection" #relative to ./minigpt4

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: tumor_detection