datasets:
  rocov2: # name of the dataset builder
    # dataset_card: dataset_card/roco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: MINIGPTv2_DATASET/rocov2/annotations/train_captions.json
          storage: MINIGPTv2_DATASET/rocov2/annotations/train_captions.json
        validation:
          url: MINIGPTv2_DATASET/rocov2/annotations/valid_captions.json
          storage: MINIGPTv2_DATASET/rocov2/annotations/valid_captions.json
      images:
        storage: MINIGPTv2_DATASET/rocov2/images
        
