datasets:
  MSD_tumor_detection:
    data_type: images
    build_info:
      image_path: datasets/MSD/slices
      ann_path: datasets/MSD/annotations/MSD_tumor_train.json
      dataset: MSD_tumor_detection
      splitBy: unc